<?php
define('TEMPLATES_DIR',SOURCE_DIR.'templates'.DS);
define('PHPLIB_DIR',SOURCE_DIR.'phplib'.DS);
define('CTRL_DIR',SOURCE_DIR.'controllers'.DS);
define('DB_HOST','');
define('DB_DATABASE','');
define('DB_USERNAME','');
define('DB_PASSWORD','');
?>
